"""Generate TypeScript declarations from a module of TypedDicts, Literal aliases and constants."""

from __future__ import annotations

import collections.abc
import json
import types
import typing
from typing import Any, Literal, NotRequired, Required, Union, get_args, get_origin

HEADER = "// Generated by tools/gen_ts_types.py from framelab.protocol.schema — do not edit.\n"


def _ts(tp: Any, aliases: dict[Any, str], top: bool = False) -> str:
    if not top:
        try:
            if tp in aliases:
                return aliases[tp]
        except TypeError:
            pass
    if tp is Any:
        return "unknown"
    if tp is str:
        return "string"
    if tp in (int, float):
        return "number"
    if tp is bool:
        return "boolean"
    if tp is None or tp is type(None):
        return "null"
    origin = get_origin(tp)
    if origin in (NotRequired, Required):
        return _ts(get_args(tp)[0], aliases)
    if origin is Literal:
        return " | ".join(json.dumps(v) for v in get_args(tp))
    if origin in (Union, types.UnionType):
        return " | ".join(_ts(a, aliases) for a in get_args(tp))
    if origin in (list, collections.abc.Sequence):
        inner = _ts(get_args(tp)[0], aliases)
        return f"{inner}[]" if inner.isidentifier() else f"Array<{inner}>"
    if origin is dict:
        return f"Record<string, {_ts(get_args(tp)[1], aliases)}>"
    if typing.is_typeddict(tp):
        return tp.__name__
    raise TypeError(f"cannot translate {tp!r} to TypeScript")


def render_module(module: types.ModuleType) -> str:
    consts: list[tuple[str, Any]] = []
    aliases: dict[Any, str] = {}
    dicts: list[type] = []
    for name, obj in vars(module).items():
        if name.startswith("_"):
            continue
        if typing.is_typeddict(obj) and obj.__module__ == module.__name__:
            dicts.append(obj)
        elif get_origin(obj) is Literal:
            aliases[obj] = name
        elif name.isupper() and isinstance(obj, (int, str)) and not isinstance(obj, bool):
            consts.append((name, obj))
    lines = [HEADER]
    for name, value in consts:
        lines.append(f"export const {name} = {json.dumps(value)} as const;")
    for alias, name in aliases.items():
        lines.append(f"export type {name} = {_ts(alias, aliases, top=True)};")
    for td in dicts:
        hints = typing.get_type_hints(td, include_extras=True)
        lines.append("")
        lines.append(f"export interface {td.__name__} {{")
        for key, tp in hints.items():
            optional = "?" if key in td.__optional_keys__ else ""
            lines.append(f"  {key}{optional}: {_ts(tp, aliases)};")
        lines.append("}")
    return "\n".join(lines) + "\n"
